import { Post } from '../types/blog';

export const samplePosts: Post[] = [
  {
    id: 1,
    title: 'Sample Blog Post 1',
    createdAt: '2023-03-14',
    updatedAt: '2023-03-15',
    category: 'Technology',
    content: 'This is a sample blog post about technology...',
    author: 'Bob Suzuki',
  },
  {
    id: 2,
    title: 'Sample Blog Post 2',
    createdAt: '2023-03-15',
    updatedAt: '2023-03-16',
    category: 'Travel',
    content: 'This is a sample blog post about traveling...',
    author: 'Bob Suzuki',
  },
  {
    id: 3,
    title: 'Sample Blog Post 3',
    createdAt: '2023-03-16',
    updatedAt: '2023-03-17',
    category: 'Food',
    content: 'This is a sample blog post about food...',
    author: 'Bob Suzuki',
  },
  {
    id: 4,
    title: 'Sample Blog Post 4',
    createdAt: '2023-03-17',
    updatedAt: '2023-03-18',
    category: 'Lifestyle',
    content: 'This is a sample blog post about lifestyle...',
    author: 'Bob Suzuki',
  },
  {
    id: 5,
    title: 'Sample Blog Post 5',
    createdAt: '2023-03-18',
    updatedAt: '2023-03-19',
    category: 'Photography',
    content: 'This is a sample blog post about photography...',
    author: 'Bob Suzuki',
  },
  {
    id: 6,
    title: 'Sample Blog Post 6',
    createdAt: '2023-03-19',
    updatedAt: '2023-03-20',
    category: 'Health',
    content: 'This is a sample blog post about health...',
    author: 'Bob Suzuki',
  },
  {
    id: 7,
    title: 'Sample Blog Post 7',
    createdAt: '2023-03-20',
    updatedAt: '2023-03-21',
    category: 'Finance',
    content: 'This is a sample blog post about finance...',
    author: 'Bob Suzuki',
  },
  {
    id: 8,
    title: 'Sample Blog Post 8',
    createdAt: '2023-03-21',
    updatedAt: '2023-03-22',
    category: 'Programming',
    content: 'This is a sample blog post about programming...',
    author: 'Bob Suzuki',
  },
  {
    id: 9,
    title: 'Sample Blog Post 9',
    createdAt: '2023-03-22',
    updatedAt: '2023-03-23',
    category: 'Design',
    content: 'This is a sample blog post about design...',
    author: 'Bob Suzuki',
  },
  {
    id: 10,
    title: 'Sample Blog Post 10',
    createdAt: '2023-03-23',
    updatedAt: '2023-03-24',
    category: 'Music',
    content: 'This is a sample blog post about music...',
    author: 'Bob Suzuki',
  },
];
